services:
  app:
    image: node:lts-alpine
    working_dir: /tmp/app
    volumes:
      - .:/tmp/app
    environment:
      PORT: 1234
    ports:
      - 1234:1234
    command:
      - npm
      - run
      - dev
  npm:
    image: node:lts-alpine
    working_dir: /tmp/app
    volumes:
      - .:/tmp/app
    entrypoint:
      - npm
  ncu:
    image: node:lts-alpine
    working_dir: /tmp/app
    volumes:
      - .:/tmp/app
    entrypoint:
      - npx
      - --yes
      - npm-check-updates
